-   id: check-whitespace
    name: check filenames for whitespace
    description: checks that filenames do not contain whitespace.
    entry: check-whitespace
    language: python
-   id: check-mixed-case
    name: check filenames for mixed case
    description: checks that filenames do not upper and lower case letters.
    entry: check-mixed-case
    language: python
-   id: check-snake-case
    name: check filenames for mixed snake/sausage case
    description: checks that filenames that are a mixture of snake and sausage case.
    entry: check-snake-case
    language: python
-   id: check-heading-levels
    name: check consistent heading levels
    description: check that heading levels do not increase by more that one.
    entry: check-heading-levels
    language: python
    types: [jupyter]
-   id: insert-toc
    name: insert a table of contents into a notebook
    description: insert a table of contents into a notebook based on its headings
    args: ['--in-place']
    entry: insert-toc
    language: python
    types: [jupyter]
-   id: hide-solution-cells
    name: hide solution cells of a notebook
    description: hides the solution cells of a notebook in a <details> html tag
    entry: hide-cells
    language: python
    types: [jupyter]
