-   id: check-filenames
    name: check filenames for whitespace
    description: checks that filenames do not contain whitespace.
    entry: check-filenames
    language: python
-   id: check-mixed-case
    name: check filenames for mixed case
    description: checks that filenames do not upper and lower case letters.
    entry: check-mixed-case
    language: python
